/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/HumanModel.glb 
Author: C.J..Goldman (https://sketchfab.com/C.J..Goldman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/male-anatomy-figure-e39449c8c59346788834b94706faf4bb
Title: Male anatomy figure
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function HumanModel(props) {
  const { nodes, materials } = useGLTF('/HumanModel.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/HumanModel.glb')
