import { Canvas } from "@react-three/fiber";
import { useGLTF, Stage, PresentationControls } from "@react-three/drei";


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 male_base_mesh_with_muscle_detail.glb 
Author: C.J..Goldman (https://sketchfab.com/C.J..Goldman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/male-base-mesh-with-muscle-detail-244061a0323b4d2e9c60d9aba374c937
Title: Male base mesh with muscle detail
*/


function Model(props) {
    const { scene } = useGLTF("/HumanModel.glb");
    return <primitive object={scene} {...props} />
  }

function Human(){

    return(
        
    <Canvas dpr={[1,2]} shadows camera={{ fov: 45 }} style={{"position": "absolute", width: "100%", height: "100%"}}>
      <color attach="background" args={["#9E9E9E"]} />
      <PresentationControls speed={2} global zoom={1} polar={[-0.1, Math.PI / 4]}>
        <Stage environment={"sunset"}>
          <Model scale={0.01} />
        </Stage>
      </PresentationControls>
    </Canvas>

    );

}

export default Human;